// JSON generated by scripts/updatePhysicalLayouts.ts
// DO NOT EDIT JSON DIRECTLY
// Run `pnpm layouts path/to/zmk`
import type { Key, KeyId } from '~/types';
import { ulid } from 'ulidx';
import data from './physicalLayouts.json';

export interface LayoutEntry {
  name: string;
  keys: Key[];
}

export type Layouts = Record<string, LayoutEntry[]>;

export function getLayouts(): Layouts {
  const layouts: Layouts = {};
  for (const [category, compactLayouts] of Object.entries(data)) {
    layouts[category] = compactLayouts.map((compact) => ({
      name: compact.name,
      keys: compact.keys.map((key) => {
        const [row, col, w, h, x, y, r, rx, ry] = key;
        return {
          id: ulid() as KeyId,
          part: 0,
          row,
          col,
          w: w / 100,
          h: h / 100,
          x: x / 100,
          y: y / 100,
          r: r / 100,
          rx: rx / 100,
          ry: ry / 100,
        } satisfies Key;
      }),
    }));
  }
  return layouts;
}
