name: Smoke Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  smoke:
    name: List test cases
    runs-on: ubuntu-latest
    outputs:
      json-files: ${{ steps.list-data-files.outputs.json-files }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: "10.34.4"
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
        env:
          CXXFLAGS: "-std=c++20"
      - id: list-data-files
        name: List all example JSON files
        run: pnpm run smoke list
  for-each-repo:
    name: Repo
    needs: smoke
    strategy:
      fail-fast: false
      matrix:
        json-path: ${{ fromJson(needs.smoke.outputs.json-files) }}
    uses: ./.github/workflows/smoke-single.yml
    with:
      json-path: ${{ matrix.json-path }}
